"""Deformations preserve legacy distributions statistically; new code is
golden-value-deterministic with a seeded RNG."""

import numpy as np
import pytest
from ase.build import bulk

from pyiron_workflow_assyst.structure.deformations import (
    apply_rattle,
    apply_shear_strain,
    apply_triaxial_strain,
)

# Generated by the snippet in the C3 task spec, Step 3 — pixi env + seed 42.
RATTLE_POSITIONS = [
    [0.030910089568138142, -0.10735508010311161, 0.07462047075908879],
    [0.09540961619779398, 1.6566963788729852, 1.6603334538093526],
    [1.8388636796807762, -0.032644968927255866, 1.7881439471080711],
    [1.739364096186417, 1.9488752469657704, 0.07733907374477597],
]
RATTLE_CELL = [
    [3.651791443229039, 0.0, 0.0],
    [0.0, 3.716194180777499, 0.0],
    [0.0, 0.0, 3.5796291115778396],
]
TRIAX_CELL = [
    [3.6986241774801467, 0.0, 0.0],
    [0.0, 3.577996238310739, 0.0],
    [0.0, 0.0, 3.729095251168098],
]
SHEAR_CELL = [
    [3.6, -0.022003761689261176, 0.12909525116809767],
    [0.07105249046137102, 3.6, 0.17122404658923215],
    [0.0940102927165271, 0.1029831498997034, 3.6],
]


@pytest.fixture
def cu():
    return bulk("Cu", "fcc", a=3.6, cubic=True)


class TestGoldenSelfIdentity:
    def test_rattle(self, cu):
        rng = np.random.default_rng(42)
        out = apply_rattle(cu, displacement=0.1, max_cell_strain=0.05, rng=rng)
        np.testing.assert_allclose(out.get_positions(), RATTLE_POSITIONS, atol=1e-12)
        np.testing.assert_allclose(out.cell.array, RATTLE_CELL, atol=1e-12)

    def test_triaxial(self, cu):
        rng = np.random.default_rng(42)
        out = apply_triaxial_strain(cu, max_strain=0.05, rng=rng)
        np.testing.assert_allclose(out.cell.array, TRIAX_CELL, atol=1e-12)

    def test_shear(self, cu):
        rng = np.random.default_rng(42)
        out = apply_shear_strain(cu, max_strain=0.05, rng=rng)
        np.testing.assert_allclose(out.cell.array, SHEAR_CELL, atol=1e-12)


class TestRNGContract:
    def test_no_rng_does_not_crash(self, cu):
        apply_rattle(cu)
        apply_triaxial_strain(cu)
        apply_shear_strain(cu)


class TestDistributionMatchesLegacy:
    """1000-sample mean check vs the frozen legacy implementation."""

    @pytest.fixture(scope="class")
    def legacy(self):
        import importlib.util
        import pathlib

        p = (
            pathlib.Path(__file__).resolve().parents[2]
            / "_legacy_assyst"
            / "deformations_legacy.py"
        )
        spec = importlib.util.spec_from_file_location("_legacy_def", p)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        return mod

    def test_rattle_displacement_mean(self, cu, legacy):
        from pymatgen.io.ase import AseAtomsAdaptor

        pmg = AseAtomsAdaptor.get_structure(cu)
        np.random.seed(0)
        legacy_norms = []
        for _ in range(1000):
            r = legacy.apply_rattle(pmg, displacement=0.1, max_cell_strain=0.0)
            legacy_norms.append(
                np.linalg.norm(
                    np.array([s.coords for s in r]) - np.array([s.coords for s in pmg])
                )
            )
        legacy_mean = float(np.mean(legacy_norms))

        rng = np.random.default_rng(0)
        new_norms = []
        base = cu.get_positions()
        for _ in range(1000):
            r = apply_rattle(cu, displacement=0.1, max_cell_strain=0.0, rng=rng)
            new_norms.append(float(np.linalg.norm(r.get_positions() - base)))
        new_mean = float(np.mean(new_norms))

        assert abs(legacy_mean - new_mean) < 0.03, (
            f"legacy mean rattle norm = {legacy_mean:.4f}, "
            f"new mean = {new_mean:.4f}; diff exceeds 5σ_mean"
        )

    def test_triaxial_strain_mean(self, cu, legacy):
        from pymatgen.io.ase import AseAtomsAdaptor

        pmg = AseAtomsAdaptor.get_structure(cu)

        # Average volume after a 0.05 triaxial strain — strain factor per axis
        # is U(1-0.05, 1+0.05), so E[V/V0] = E[∏(1+εᵢ)] = 1 (uniform mean 0).
        np.random.seed(0)
        legacy_dvol = []
        v0 = pmg.volume
        for _ in range(1000):
            t = legacy.apply_triaxial_strain(pmg, max_strain=0.05)
            legacy_dvol.append((t.volume - v0) / v0)
        legacy_mean = float(np.mean(legacy_dvol))

        rng = np.random.default_rng(0)
        new_dvol = []
        v0_ase = cu.get_volume()
        for _ in range(1000):
            t = apply_triaxial_strain(cu, max_strain=0.05, rng=rng)
            new_dvol.append((t.get_volume() - v0_ase) / v0_ase)
        new_mean = float(np.mean(new_dvol))

        # Both should be ~0 (uniform mean); allow ±0.005 (well within 3σ_mean).
        assert abs(legacy_mean) < 0.005
        assert abs(new_mean) < 0.005
        assert abs(legacy_mean - new_mean) < 0.005

    def test_shear_strain_mean(self, cu, legacy):
        from pymatgen.io.ase import AseAtomsAdaptor

        pmg = AseAtomsAdaptor.get_structure(cu)

        np.random.seed(0)
        legacy_off = []
        for _ in range(1000):
            s = legacy.apply_shear_strain(pmg, max_strain=0.05)
            # mean of off-diagonal magnitude
            m = np.asarray(s.lattice.matrix) - np.asarray(pmg.lattice.matrix)
            legacy_off.append(np.mean(np.abs(m)))
        legacy_mean = float(np.mean(legacy_off))

        rng = np.random.default_rng(0)
        new_off = []
        for _ in range(1000):
            s = apply_shear_strain(cu, max_strain=0.05, rng=rng)
            m = s.cell.array - cu.cell.array
            new_off.append(np.mean(np.abs(m)))
        new_mean = float(np.mean(new_off))

        # Both should reflect the same uniform half-range distribution.
        assert (
            abs(legacy_mean - new_mean) / legacy_mean < 0.10
        ), f"legacy = {legacy_mean:.5f}, new = {new_mean:.5f}"
