"""Deformations preserve legacy distributions statistically; new code is
golden-value-deterministic with a seeded RNG."""

import numpy as np
import pytest
from ase.build import bulk

from pyiron_workflow_assyst.structure.deformations import (
    apply_rattle,
    apply_shear_strain,
    apply_triaxial_strain,
)

# Generated by the snippet in the C3 task spec, Step 3 — pixi env + seed 42.
RATTLE_POSITIONS = [
    [0.030910089568138142, -0.10735508010311161, 0.07462047075908879],
    [0.09540961619779398, 1.6566963788729852, 1.6603334538093526],
    [1.8388636796807762, -0.032644968927255866, 1.7881439471080711],
    [1.739364096186417, 1.9488752469657704, 0.07733907374477597],
]
RATTLE_CELL = [
    [3.651791443229039, 0.0, 0.0],
    [0.0, 3.716194180777499, 0.0],
    [0.0, 0.0, 3.5796291115778396],
]
TRIAX_CELL = [
    [3.6986241774801467, 0.0, 0.0],
    [0.0, 3.577996238310739, 0.0],
    [0.0, 0.0, 3.729095251168098],
]
SHEAR_CELL = [
    [3.6, -0.022003761689261176, 0.12909525116809767],
    [0.07105249046137102, 3.6, 0.17122404658923215],
    [0.0940102927165271, 0.1029831498997034, 3.6],
]


@pytest.fixture
def cu():
    return bulk("Cu", "fcc", a=3.6, cubic=True)


class TestGoldenSelfIdentity:
    def test_rattle(self, cu):
        rng = np.random.default_rng(42)
        out = apply_rattle(cu, displacement=0.1, max_cell_strain=0.05, rng=rng)
        np.testing.assert_allclose(out.get_positions(), RATTLE_POSITIONS, atol=1e-12)
        np.testing.assert_allclose(out.cell.array, RATTLE_CELL, atol=1e-12)

    def test_triaxial(self, cu):
        rng = np.random.default_rng(42)
        out = apply_triaxial_strain(cu, max_strain=0.05, rng=rng)
        np.testing.assert_allclose(out.cell.array, TRIAX_CELL, atol=1e-12)

    def test_shear(self, cu):
        rng = np.random.default_rng(42)
        out = apply_shear_strain(cu, max_strain=0.05, rng=rng)
        np.testing.assert_allclose(out.cell.array, SHEAR_CELL, atol=1e-12)


class TestRNGContract:
    def test_no_rng_does_not_crash(self, cu):
        apply_rattle(cu)
        apply_triaxial_strain(cu)
        apply_shear_strain(cu)


class TestDistributionMatchesLegacy:
    """1000-sample mean check vs the frozen legacy implementation."""

    @pytest.fixture(scope="class")
    def legacy(self):
        """Import the legacy deformations from the snapshot. Skip if import fails."""
        import importlib.util
        import pathlib
        import sys

        snap = (
            pathlib.Path(__file__).resolve().parents[2]
            / "_legacy_assyst"
            / "workflow.py"
        )
        spec = importlib.util.spec_from_file_location("_legacy_assyst_workflow", snap)
        mod = importlib.util.module_from_spec(spec)
        try:
            sys.modules["_legacy_assyst_workflow"] = mod
            spec.loader.exec_module(mod)
        except Exception as e:
            pytest.skip(f"Legacy workflow.py could not be imported: {e}")
        return mod

    def test_rattle_displacement_mean(self, cu, legacy):
        from pymatgen.io.ase import AseAtomsAdaptor

        pmg = AseAtomsAdaptor.get_structure(cu)
        np.random.seed(0)
        legacy_norms = []
        for _ in range(1000):
            r = legacy.apply_rattle(pmg, displacement=0.1, max_cell_strain=0.0)
            legacy_norms.append(
                np.linalg.norm(
                    np.array([s.coords for s in r]) - np.array([s.coords for s in pmg])
                )
            )
        legacy_mean = float(np.mean(legacy_norms))

        rng = np.random.default_rng(0)
        new_norms = []
        base = cu.get_positions()
        for _ in range(1000):
            r = apply_rattle(cu, displacement=0.1, max_cell_strain=0.0, rng=rng)
            new_norms.append(float(np.linalg.norm(r.get_positions() - base)))
        new_mean = float(np.mean(new_norms))

        # sigma_mean approx stdev_per_norm / sqrt(N). Empirically stdev_per_norm approx 0.18 here,
        # so sigma_mean approx 0.006. Allow 5sigma for headroom: |mean_diff| < 0.03.
        assert abs(legacy_mean - new_mean) < 0.03, (
            f"legacy mean rattle norm = {legacy_mean:.4f}, "
            f"new mean = {new_mean:.4f}; diff exceeds 5sigma_mean"
        )
